In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
file_path = 'Inputs.xlsx'
dataset=pd.read_excel(file_path)
x=dataset.iloc[2:,2:-1].values
y=dataset.iloc[2:,-1].values

In [5]:
print(x)

[[52.6 76.6 19.2 ... 0 600 2]
 [52.6 76.6 19.2 ... 0 600 2.3]
 [52.6 76.6 19.2 ... 0 900 1.8]
 ...
 [38.1 66 13.6 ... 0.2388 1500 1.8]
 [38.1 66 13.6 ... 0.2388 1500 2]
 [38.1 66 13.6 ... 0.2388 1500 2.3]]


In [7]:
print(y)

[47.4900692 44.0212568 103.090293 98.0306171 92.0327738 120.695862
 117.973042 114.246795 137.594684 137.103579 135.643063 119.083949
 113.581613 107.325081 223.451568 215.423479 205.202528 256.163744
 252.699618 247.067974 287.612614 288.357209 287.151583 54.5844441
 47.6059779 40.1867174 146.405566 133.971542 120.409132 182.754255
 174.44631 164.795386 217.872122 213.737578 208.129133 171.557512
 168.832244 164.470379 280.128094 277.743054 272.585691 309.384675
 310.907001 310.20901 338.032976 342.998919 346.221891 69.4333031
 65.407838 60.9394313 140.059377 133.864298 126.318114 162.394769
 159.285135 154.779523 183.880081 183.676551 182.167157 40.0930395
 32.8929284 25.2785053 129.029184 115.98735 101.964396 165.852115
 156.800686 146.568687 201.55345 196.573817 190.265646 25.7707222
 18.6693525 11.1905385 105.637114 92.5380291 78.644788 142.324015
 132.897781 122.514736 177.990661 172.341626 165.588549 37.5444388
 35.0107133 32.2489806 77.5150042 73.2956993 68.4072638 91.7893871
 

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,test_size=0.2,random_state=0)


In [10]:
print ('The shape of x_train is:', x_train.shape)
print ('The shape of y_train is: ', y_train.shape)
print ('Number of training examples (m):', len(x_train))

The shape of x_train is: (786, 11)
The shape of y_train is:  (786,)
Number of training examples (m): 786


In [13]:
print(f'x_train is numpy array: {isinstance(x_train, np.ndarray)}')
print(f'y_train is numpy array: {isinstance(y_train, np.ndarray)}')

x_train is numpy array: True
y_train is numpy array: True


In [15]:
def compute_cost(x, y, w, b,theta,beta):
    """
    Computes the cost function for linear regression with eleven variables using a for loop.

    Args:
        x (ndarray): Shape (m, 11) Input to the model (four features of the training examples)
        y (ndarray): Shape (m,) Label (Actual output values for the training examples)
        w (ndarray): Shape (11,) Parameters of the model (weights for the four features)
        b (scalar): Parameter of the model (bias)

    Returns:
        total_cost (float): The cost of using w, b as the parameters for linear regression
                            to fit the data points in x and y.
    """
    # Number of training examples
    m,n = x.shape

    # Initialize total cost
    total_cost = 0

    # Compute the total cost using a for loop
    for i in range(m):
        f_wb_i = b  # Start with the bias term
        for j in range(n):  # Sum over all features
            f_wb_i += w[j] * x[i, j] + theta[j] * x[i, j]**2 + beta[j] * x[i, j]**3
        total_cost += (f_wb_i - y[i]) ** 2  # Sum of squared errors

    # Compute the average cost
    total_cost = total_cost / (2 * m)

    return total_cost

In [17]:
m,n=x_train.shape
initial_w = np.zeros(n)
initial_theta=np.zeros(n)
initial_beta=np.zeros(n)
initial_b =0.5

cost = compute_cost(x_train, y_train, initial_w, initial_b,initial_theta,initial_beta)
print(type(cost))
print(f'Cost at initial w: {cost:.3f}')


<class 'numpy.float64'>
Cost at initial w: 15492.574


In [19]:
def compute_gradient(x, y, w, b,theta,beta):
    """
    Computes the gradient for linear regression with multiple variables.

    Args:
        x (ndarray): Shape (m, n) Input to the model (features of the training examples)
        y (ndarray): Shape (m,) Label (actual output values for the training examples)
        w (ndarray): Shape (n,) Parameters of the model (weights for the features)
        b (scalar): Parameter of the model (bias)

    Returns:
        dj_dw (ndarray): Shape (n,) The gradient of the cost w.r.t. the parameters w
        dj_db (scalar): The gradient of the cost w.r.t. the parameter b
    """
    # Number of training examples
    m, n = x.shape
  
    # Initialize gradients
    dj_dw = np.zeros(n)
    dj_dtheta = np.zeros(n)
    dj_dbeta = np.zeros(n)
    dj_db = 0.0
    for i in range(m):
        f_wb_i = np.dot(x[i], w) + np.dot(x[i]**2,theta)+ + np.dot(x[i]**3,beta) + b  # Predicted value
        error = f_wb_i - y[i]  # Error term
        for j in range(n):
            dj_dw[j] += error * x[i, j]  # Gradient for w[j]
            dj_dtheta[j] += error * x[i, j]**2
            dj_dbeta[j] += error * x[i, j]**3
        dj_db += error  # Gradient for b

    # Average the gradients
    dj_dw /= m
    dj_dtheta /= m
    dj_dbeta /= m
    dj_db/= m


    return dj_dw, dj_db,dj_dtheta, dj_dbeta

In [21]:
m,n=x_train.shape
initial_w = np.zeros(n)
initial_theta=np.zeros(n)
initial_beta=np.zeros(n)
initial_b = 0

tmp_dj_dw, tmp_dj_db,tmp_dj_dtheta,tmp_dj_dbeta = compute_gradient(x_train, y_train, initial_w, initial_b,initial_theta,initial_beta)
print(f'dj_dw,dj_dtheta at initial w, b,theta (zeros): {tmp_dj_dw}')
print('Gradient at initial w, b (zeros):', tmp_dj_dw, tmp_dj_db,tmp_dj_dtheta,tmp_dj_dbeta)

dj_dw,dj_dtheta at initial w, b,theta (zeros): [-1.92084471e+03 -1.18122074e+04 -2.83832397e+03 -9.14164787e+02
 -7.63096803e+03 -5.88547603e+03 -9.57593021e+02 -1.54255794e+02
 -2.13193441e+01 -1.81230735e+05 -3.15137241e+02]
Gradient at initial w, b (zeros): [-1.92084471e+03 -1.18122074e+04 -2.83832397e+03 -9.14164787e+02
 -7.63096803e+03 -5.88547603e+03 -9.57593021e+02 -1.54255794e+02
 -2.13193441e+01 -1.81230735e+05 -3.15137241e+02] -155.6377700388498 [-4.38318436e+04 -9.02534072e+05 -5.57854156e+04 -1.25276880e+04
 -3.75821691e+05 -2.29657750e+05 -6.02782003e+03 -4.10024277e+02
 -9.28203371e+00 -2.25608162e+08 -6.44716915e+02] [-1.61983864e+06 -6.93734729e+07 -1.16852226e+06 -2.93593305e+05
 -1.85884700e+07 -9.09740831e+06 -3.90343273e+04 -2.44664994e+03
 -8.03873283e+00 -2.94846889e+11 -1.33266037e+03]


In [23]:
def gradient_descent(x, y, w_in, b_in,theta_in, beta_in, cost_function, gradient_function, alpha, num_iters):
    """
    Performs batch gradient descent to learn theta. Updates theta by taking
    num_iters gradient steps with learning rate alpha.

    Args:
        x : (ndarray): Shape (m, n) Input data (features of the training examples).
        y : (ndarray): Shape (m,) Output data (actual output values for the training examples).
        w_in : (ndarray): Shape (n,) Initial values of parameters (weights) of the linear term.
        theta_in : ndarray): Shape (n,) Initial values of parameters (weights) of the quadratic term.
         
        b_in : (scalar) Initial value of parameter (bias) of the model.
        cost_function : function to compute cost.
        gradient_function : function to compute the gradient.
        alpha : (float) Learning rate.
        num_iters : (int) Number of iterations to run gradient descent.

    Returns:
        w : (ndarray): Shape (n,) Updated values of parameters (weights) of the model after running gradient descent.
        b : (scalar) Updated value of parameter (bias) of the model after running gradient descent.
        J_history : List of costs at each iteration.
        w_history : List of weights at each iteration.
    """
    m, n = x.shape
    # Initialize parameters
    w = copy.deepcopy(w_in)  # Avoid modifying global w within function
    theta=copy.deepcopy(theta_in)
    beta=copy.deepcopy(beta_in)
    b = b_in

    # History of cost and weights
    J_history = []
    w_history = []

    for i in range(num_iters):
        # Calculate the gradient and update the parameters
        dj_dw, dj_db,dj_dtheta,dj_dbeta = gradient_function(x, y, w, b,theta,beta)

        # Update Parameters using w, theta, b, alpha, and gradient
        for j in range(n):
            w[j] = w[j] - alpha * dj_dw[j]
            theta[j] = theta[j] - alpha * dj_dtheta[j]
            beta[j] = beta[j] - alpha * dj_dbeta[j]
        b = b - alpha * dj_db

        # Save cost J at each iteration
        if i < 10000000:  # Prevent resource exhaustion
            cost = cost_function(x, y, w, b,theta,beta)
            J_history.append(cost)

        # Print cost every at intervals 10 times or as many iterations if < 10
        if i % math.ceil(num_iters / 100) == 0:
            w_history.append(w.copy())
            print(f"Iteration {i:4}: Cost {float(J_history[-1]):15.2f}")

    return w, b,theta,beta, J_history, w_history  # Return w and J, w history for graphing

In [86]:
import copy
import math
m,n=x_train.shape
iinitial_w = np.array([-5.8, 2.7, 0.741, -10.8, 10.5, -12.54,8.98, -1.04, -0.75, 0.41, -0.7])
initial_theta=np.array([0.000052, 0.000002, 0.00000004, 0.000025, 0.00008, 0.00009, 0.000041, 0.0002, 0.00012, 0.00034, 0.0000045])
initial_beta=np.array([0.0001, 0.0000002, 0.0000001, 0.00000005, 0.0003, 0.003, 0.0000002, 0.0000001, 0.0000004, 0.0035, 0.0015])
initial_b=-40

# Define the learning rate and number of iterations
alpha = 0.000000000000000000000047
iterations = 150000
# Perform gradient descent
w, b, theta,beta,_,_ = gradient_descent(x_train, y_train, initial_w, initial_b,initial_theta, initial_beta,compute_cost, compute_gradient, alpha, iterations)

print("w, b found by gradient descent:", w, b,theta,beta)

Iteration    0: Cost 23413705339368.43
Iteration 1500: Cost 13655732691011.09
Iteration 3000: Cost 7964524737696.93
Iteration 4500: Cost 4645203282812.74
Iteration 6000: Cost 2709253127549.37
Iteration 7500: Cost 1580135910490.01
Iteration 9000: Cost 921593289238.27
Iteration 10500: Cost 537507051376.65
Iteration 12000: Cost 313493854122.55
Iteration 13500: Cost 182841131902.18
Iteration 15000: Cost 106639666841.92
Iteration 16500: Cost  62196174363.17
Iteration 18000: Cost  36275097620.79
Iteration 19500: Cost  21156973863.86
Iteration 21000: Cost  12339528963.64
Iteration 22500: Cost   7196871328.46
Iteration 24000: Cost   4197484561.43
Iteration 25500: Cost   2448132063.86
Iteration 27000: Cost   1427845452.48
Iteration 28500: Cost    832776836.63
Iteration 30000: Cost    485710969.44
Iteration 31500: Cost    283289411.71
Iteration 33000: Cost    165229726.49
Iteration 34500: Cost     96372983.02
Iteration 36000: Cost     56213201.86
Iteration 37500: Cost     32790542.86
Iteration 3

In [88]:
print('The shape of x_test is:', x_test.shape)

The shape of x_test is: (197, 11)


In [90]:
from IPython.display import FileLink
k=x_test.shape[0]
data=[]
for i in range(k):
        f_wb_i = b  # Start with the bias term
        for j in range(11):  # Sum over all features
            f_wb_i += w[j] * x_test[i, j]+theta[j] * x_test[i, j]**2 + beta[j] * x_test[i, j]**3
        print(f_wb_i, y_test[i])
        row= [f_wb_i,y_test[i]]
        data.append(row)
df=pd.DataFrame(data,columns=['Predicted','Actual'])
file_name='Result_Cubic_Regression2.xlsx'
df.to_excel(file_name, index=False)
FileLink(file_name)


280.36007076140356 223.154376
180.06788375874874 207.188186
264.88442324363547 133.971542
275.2096884740223 219.292928
294.9382286769084 174.687108
253.74936193210314 57.1057396
286.195354637433 175.320837
147.17072017078868 249.387055
289.075058981461 44.9859809
281.41257844505486 34.5454599
297.9015534567165 44.2105264
107.2159049885533 166.013301
56.949775090959896 436.789023
253.7405663441075 247.122796
310.5812556554082 182.545969
275.7198572281167 223.451568
302.2530657168075 17.0370557
280.41484304097725 200.170248
213.7348630241186 244.041376
56.943518786018615 428.298665
284.81978605451246 90.9434057
135.61419100882688 295.946534
101.84331613893126 342.998919
296.36895267828606 157.246183
241.32186073999165 164.795386
222.11674135052758 81.6187988
239.1029952004382 137.313404
246.7338300550883 98.6450947
194.55783241876668 221.545913
113.10956612781531 247.130103
286.1920992174642 183.966135
296.08805157542145 175.207607
79.57071529240554 104.485971
225.18872367136493 237.9636

C:\Users\Mafi\Data file\Result_Cubic_Regression2.xlsx