In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
file_path = 'Inputs_modified.xlsx'
dataset=pd.read_excel(file_path)
x=dataset.iloc[2:,2:-1].values
y=dataset.iloc[2:,-1].values

In [5]:
print(x)

[[52.6 76.6 19.2 ... 0 600 2]
 [52.6 76.6 19.2 ... 0 600 2.3]
 [52.6 76.6 19.2 ... 0 900 1.8]
 ...
 [38.1 66 13.6 ... 0.2388 1500 1.8]
 [38.1 66 13.6 ... 0.2388 1500 2]
 [38.1 66 13.6 ... 0.2388 1500 2.3]]


In [7]:
print(y)

[47.4900692 44.0212568 103.090293 98.0306171 92.0327738 120.695862
 117.973042 114.246795 137.594684 137.103579 135.643063 119.083949
 113.581613 107.325081 223.451568 215.423479 205.202528 256.163744
 252.699618 247.067974 287.612614 288.357209 287.151583 54.5844441
 47.6059779 40.1867174 146.405566 133.971542 120.409132 182.754255
 174.44631 164.795386 217.872122 213.737578 208.129133 171.557512
 168.832244 164.470379 280.128094 277.743054 272.585691 309.384675
 310.907001 310.20901 338.032976 342.998919 346.221891 69.4333031
 65.407838 60.9394313 140.059377 133.864298 126.318114 162.394769
 159.285135 154.779523 183.880081 183.676551 182.167157 40.0930395
 32.8929284 25.2785053 129.029184 115.98735 101.964396 165.852115
 156.800686 146.568687 201.55345 196.573817 190.265646 25.7707222
 18.6693525 11.1905385 105.637114 92.5380291 78.644788 142.324015
 132.897781 122.514736 177.990661 172.341626 165.588549 37.5444388
 35.0107133 32.2489806 77.5150042 73.2956993 68.4072638 91.7893871
 

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,test_size=0.2,random_state=0)


In [11]:
print ('The shape of x_train is:', x_train.shape)
print ('The shape of y_train is: ', y_train.shape)
print ('Number of training examples (m):', len(x_train))

The shape of x_train is: (783, 11)
The shape of y_train is:  (783,)
Number of training examples (m): 783


In [13]:
print(f'x_train is numpy array: {isinstance(x_train, np.ndarray)}')
print(f'y_train is numpy array: {isinstance(y_train, np.ndarray)}')

x_train is numpy array: True
y_train is numpy array: True


In [15]:
def compute_cost(x, y, w, b):
    """
    Computes the cost function for linear regression with eleven variables using a for loop.

    Args:
        x (ndarray): Shape (m, 11) Input to the model (four features of the training examples)
        y (ndarray): Shape (m,) Label (Actual output values for the training examples)
        w (ndarray): Shape (11,) Parameters of the model (weights for the four features)
        b (scalar): Parameter of the model (bias)

    Returns:
        total_cost (float): The cost of using w, b as the parameters for linear regression
                            to fit the data points in x and y.
    """
    # Number of training examples
    m = x.shape[0]

    # Initialize total cost
    total_cost = 0

    # Compute the total cost using a for loop
    for i in range(m):
        f_wb_i = b  # Start with the bias term
        for j in range(11):  # Sum over all features
            f_wb_i += w[j] * x[i, j]
        total_cost += (f_wb_i - y[i]) ** 2  # Sum of squared errors

    # Compute the average cost
    total_cost = total_cost / (2 * m)

    return total_cost

In [17]:
initial_w = np.array([0.1, 0.02, 0.01, 0.05, 0.3, 0.03, 0.02, 0.01, 0.04, 0.35, 0.15])
initial_b =0.5

cost = compute_cost(x_train, y_train, initial_w, initial_b)
print(type(cost))
print(f'Cost at initial w: {cost:.3f}')


<class 'numpy.float64'>
Cost at initial w: 31677.978


In [19]:
def compute_gradient(x, y, w, b):
    """
    Computes the gradient for linear regression with multiple variables.

    Args:
        x (ndarray): Shape (m, n) Input to the model (features of the training examples)
        y (ndarray): Shape (m,) Label (actual output values for the training examples)
        w (ndarray): Shape (n,) Parameters of the model (weights for the features)
        b (scalar): Parameter of the model (bias)

    Returns:
        dj_dw (ndarray): Shape (n,) The gradient of the cost w.r.t. the parameters w
        dj_db (scalar): The gradient of the cost w.r.t. the parameter b
    """
    # Number of training examples
    m, n = x.shape

    # Initialize gradients
    dj_dw = np.zeros(n)
    dj_db = 0.0

    # Compute the gradients
    for i in range(m):
        f_wb_i = np.dot(x[i], w) + b  # Predicted value
        error = f_wb_i - y[i]  # Error term
        for j in range(n):
            dj_dw[j] += error * x[i, j]  # Gradient for w[j]
        dj_db += error  # Gradient for b

    # Average the gradients
    dj_dw /= m
    dj_db /= m

    return dj_dw, dj_db

In [21]:
initial_w = np.array([0.1, 0.02, 0.01, 0.05, 0.3, 0.03, 0.02, 0.01, 0.04, 0.35, 0.15])
initial_b = 0

tmp_dj_dw, tmp_dj_db = compute_gradient(x_train, y_train, initial_w, initial_b)
print('Gradient at initial w, b (zeros):', tmp_dj_dw, tmp_dj_db)

Gradient at initial w, b (zeros): [3.82163783e+03 1.78270106e+04 4.12352577e+03 1.42791536e+03
 1.11713497e+04 9.17539535e+03 1.35747851e+03 2.13240954e+02
 3.20255291e+01 2.70312287e+05 4.75490238e+02] 233.7740538862323


In [23]:
def gradient_descent(x, y, w_in, b_in, cost_function, gradient_function, alpha, num_iters):
    """
    Performs batch gradient descent to learn theta. Updates theta by taking
    num_iters gradient steps with learning rate alpha.

    Args:
        x : (ndarray): Shape (m, n) Input data (features of the training examples).
        y : (ndarray): Shape (m,) Output data (actual output values for the training examples).
        w_in : (ndarray): Shape (n,) Initial values of parameters (weights) of the model.
        b_in : (scalar) Initial value of parameter (bias) of the model.
        cost_function : function to compute cost.
        gradient_function : function to compute the gradient.
        alpha : (float) Learning rate.
        num_iters : (int) Number of iterations to run gradient descent.

    Returns:
        w : (ndarray): Shape (n,) Updated values of parameters (weights) of the model after running gradient descent.
        b : (scalar) Updated value of parameter (bias) of the model after running gradient descent.
        J_history : List of costs at each iteration.
        w_history : List of weights at each iteration.
    """

    # Initialize parameters
    w = copy.deepcopy(w_in)  # Avoid modifying global w within function
    b = b_in

    # History of cost and weights
    J_history = []
    w_history = []

    for i in range(num_iters):
        # Calculate the gradient and update the parameters
        dj_dw, dj_db = gradient_function(x, y, w, b)

        # Update Parameters using w, b, alpha, and gradient
        for j in range(11):
          w[j] = w[j] - alpha * dj_dw[j]
          b = b - alpha * dj_db

        # Save cost J at each iteration
        if i < 1000000:  # Prevent resource exhaustion
            cost = cost_function(x, y, w, b)
            J_history.append(cost)

        # Print cost every at intervals 10 times or as many iterations if < 10
        if i % math.ceil(num_iters / 100) == 0:
            w_history.append(w.copy())
            print(f"Iteration {i:4}: Cost {float(J_history[-1]):8.2f}")

    return w, b, J_history, w_history  # Return w and J, w history for graphing

In [43]:
import copy
import math
initial_w = np.array([0.0001, 0.0000002, 0.0000001, 0.00000005, 0.0003, 0.003, 0.0000002, 0.0000001, 0.0000004, 0.0035, 0.0015])  # Initial weights for 11 features
initial_b = 0.0  # Initial bias

# Define the learning rate and number of iterations
alpha = 0.000001
iterations = 400000

# Perform gradient descent
w, b, _, _ = gradient_descent(x_train, y_train, initial_w, initial_b, compute_cost, compute_gradient, alpha, iterations)

print("w, b found by gradient descent:", w, b)

Iteration    0: Cost  2898.18
Iteration 4000: Cost  1785.38
Iteration 8000: Cost  1597.98
Iteration 12000: Cost  1471.99
Iteration 16000: Cost  1370.06
Iteration 20000: Cost  1282.10
Iteration 24000: Cost  1204.67
Iteration 28000: Cost  1136.06
Iteration 32000: Cost  1075.09
Iteration 36000: Cost  1020.83
Iteration 40000: Cost   972.47
Iteration 44000: Cost   929.32
Iteration 48000: Cost   890.79
Iteration 52000: Cost   856.34
Iteration 56000: Cost   825.51
Iteration 60000: Cost   797.91
Iteration 64000: Cost   773.17
Iteration 68000: Cost   750.98
Iteration 72000: Cost   731.07
Iteration 76000: Cost   713.18
Iteration 80000: Cost   697.10
Iteration 84000: Cost   682.64
Iteration 88000: Cost   669.61
Iteration 92000: Cost   657.88
Iteration 96000: Cost   647.29
Iteration 100000: Cost   637.74
Iteration 104000: Cost   629.10
Iteration 108000: Cost   621.29
Iteration 112000: Cost   614.22
Iteration 116000: Cost   607.81
Iteration 120000: Cost   601.99
Iteration 124000: Cost   596.69
Iter

In [37]:
print('The shape of x_test is:', x_test.shape)

The shape of x_test is: (197, 11)


In [47]:
from IPython.display import FileLink
k=x_test.shape[0]
data = []
for i in range(k):
        f_wb_i = b  # Start with the bias term
        for j in range(11):  # Sum over all features
            f_wb_i += w[j] * x_test[i, j]
        print(f_wb_i, y_test[i])
        row= [f_wb_i, y_test[i]]
        data.append(row)
df = pd.DataFrame(data, columns=['Predicted', 'Actual'])
file_name = 'Results_MLR.xlsx'
df.to_excel(file_name, index=False)


# Download the file
FileLink(file_name)


223.11381712311294 223.154376
204.13758946579898 207.188186
123.55597149164657 133.971542
168.564937292311 219.292928
151.68103836850293 174.687108
52.8862034435809 57.1057396
170.78376501148452 175.320837
243.5566659974027 249.387055
55.85760549714645 44.9859809
52.01141302537183 34.5454599
63.04747150709137 44.2105264
176.23651011018754 166.013301
385.4735709749581 436.789023
230.50173215329076 247.122796
183.63213955026367 182.545969
195.35457318571173 223.451568
31.558945703922983 17.0370557
190.72659537829026 200.170248
245.45650295801562 244.041376
385.618301762671 428.298665
110.9939917713529 90.9434057
267.51474712988795 295.946534
354.26962374136514 342.998919
151.14794162745153 157.246183
172.8379020268178 164.795386
106.72701273531221 81.6187988
153.0622766506428 137.313404
131.40719152800085 98.6450947
233.05880087314785 221.545913
255.00699670396475 247.130103
170.88025220329314 183.966135
154.80741533472343 175.207607
123.69884382258213 104.485971
247.764379796747 237.963

C:\Users\Mafi\Data file\Results_MLR.xlsx