In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import mean_squared_error

In [3]:
file_path = 'Inputs_modified_a.xlsx'
dataset=pd.read_excel(file_path)
x=dataset.iloc[2:,2:-1].values
y=dataset.iloc[2:,-1].values

In [5]:
print(x)

[[52.6 76.6 19.2 ... 0 600 2]
 [52.6 76.6 19.2 ... 0 600 2.3]
 [52.6 76.6 19.2 ... 0 900 1.8]
 ...
 [38.1 66 13.6 ... 0.2388 1500 1.8]
 [38.1 66 13.6 ... 0.2388 1500 2]
 [38.1 66 13.6 ... 0.2388 1500 2.3]]


In [7]:
print(y)

[47.4900692 44.0212568 103.090293 98.0306171 92.0327738 120.695862
 117.973042 114.246795 137.594684 137.103579 135.643063 119.083949
 113.581613 107.325081 223.451568 215.423479 205.202528 256.163744
 252.699618 247.067974 287.612614 288.357209 287.151583 54.5844441
 47.6059779 40.1867174 146.405566 133.971542 120.409132 182.754255
 174.44631 164.795386 217.872122 213.737578 208.129133 171.557512
 168.832244 164.470379 280.128094 277.743054 272.585691 309.384675
 310.907001 310.20901 338.032976 342.998919 346.221891 69.4333031
 65.407838 60.9394313 140.059377 133.864298 126.318114 162.394769
 159.285135 154.779523 183.880081 183.676551 182.167157 40.0930395
 32.8929284 25.2785053 129.029184 115.98735 101.964396 165.852115
 156.800686 146.568687 201.55345 196.573817 190.265646 25.7707222
 18.6693525 11.1905385 105.637114 92.5380291 78.644788 142.324015
 132.897781 122.514736 177.990661 172.341626 165.588549 37.5444388
 35.0107133 32.2489806 77.5150042 73.2956993 68.4072638 91.7893871
 

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.85,test_size=0.15,random_state=0)


In [11]:
print ('The shape of x_train is:', x_train.shape)
print ('The shape of y_train is: ', y_train.shape)
print ('Number of training examples (m):', len(x_train))

The shape of x_train is: (831, 11)
The shape of y_train is:  (831,)
Number of training examples (m): 831


In [13]:
print(f'x_train is numpy array: {isinstance(x_train, np.ndarray)}')
print(f'y_train is numpy array: {isinstance(y_train, np.ndarray)}')

x_train is numpy array: True
y_train is numpy array: True


In [15]:
def compute_cost(x, y, w, b,theta):
    """
    Computes the cost function for linear regression with eleven variables using a for loop.

    Args:
        x (ndarray): Shape (m, 11) Input to the model (four features of the training examples)
        y (ndarray): Shape (m,) Label (Actual output values for the training examples)
        w (ndarray): Shape (11,) Parameters of the model (weights for the four features)
        b (scalar): Parameter of the model (bias)

    Returns:
        total_cost (float): The cost of using w, b as the parameters for linear regression
                            to fit the data points in x and y.
    """
    # Number of training examples
    m,n = x.shape

    # Initialize total cost
    total_cost = 0
    f_wb=np.zeros(m)

    # Compute the total cost using a for loop
    for i in range(m):
        f_wb[i] = b  # Start with the bias term
        for j in range(n):  # Sum over all features
            f_wb[i] += w[j] * x[i, j] + theta[j] * x[i, j]**2
        total_cost += (f_wb[i] - y[i]) ** 2  # Sum of squared errors

    # Compute the average cost
    total_cost = total_cost / (2 * m)

    return total_cost

In [17]:
m,n=x_train.shape
initial_w = np.zeros(n)
initial_theta=np.zeros(n)
initial_b =0.5

cost = compute_cost(x_train, y_train, initial_w, initial_b,initial_theta)
print(type(cost))
print(f'Cost at initial w: {cost:.3f}')


<class 'numpy.float64'>
Cost at initial w: 15314.256


In [26]:
def compute_gradient(x, y, w, b,theta):
    """
    Computes the gradient for linear regression with multiple variables.

    Args:
        x (ndarray): Shape (m, n) Input to the model (features of the training examples)
        y (ndarray): Shape (m,) Label (actual output values for the training examples)
        w (ndarray): Shape (n,) Parameters of the model (weights for the features)
        b (scalar): Parameter of the model (bias)

    Returns:
        dj_dw (ndarray): Shape (n,) The gradient of the cost w.r.t. the parameters w
        dj_db (scalar): The gradient of the cost w.r.t. the parameter b
    """
    # Number of training examples
    m, n = x.shape
    total_cost = np.zeros(m)
    # Initialize gradients
    dj_dw = np.zeros(n)
    dj_dtheta = np.zeros(n)
    dj_db = 0.0
    f_wb=np.zeros(m)
    error=np.zeros(m)
    for i in range(m):
        f_wb[i] = np.dot(w.T,x[i,:]) + np.dot(theta.T,x[i,:]**2)+ b  # Predicted value
        error[i] = f_wb[i] - y[i]  # Error term
        for j in range(n):
            dj_dw[j] += error[i] * x[i, j]  # Gradient for w[j]
            dj_dtheta[j] += error[i] * x[i, j]**2
        dj_db += error[i]  # Gradient for b

    # Average the gradients
    dj_dw = (dj_dw) / m
    dj_dtheta = (dj_dtheta) / m
    dj_db= (dj_db)/ m


    return dj_dw, dj_db,dj_dtheta

In [27]:
m,n=x_train.shape
initial_w = np.zeros(n)
initial_theta=np.zeros(n)
initial_b = 0

tmp_dj_dw, tmp_dj_db,tmp_dj_dtheta = compute_gradient(x_train, y_train, initial_w, initial_b,initial_theta)
print(f'dj_dw,dj_dtheta at initial w, b,theta (zeros): {tmp_dj_dw}')
print('Gradient at initial w, b (zeros):', tmp_dj_dw, tmp_dj_db,tmp_dj_dtheta)

dj_dw,dj_dtheta at initial w, b,theta (zeros): [-1.93397960e+03 -1.18554702e+04 -2.84273910e+03 -8.46926755e+02
 -7.61888120e+03 -5.95703070e+03 -9.55185591e+02 -1.45760182e+02
 -2.04012262e+01 -1.82022002e+05 -3.14060370e+02]
Gradient at initial w, b (zeros): [-1.93397960e+03 -1.18554702e+04 -2.84273910e+03 -8.46926755e+02
 -7.61888120e+03 -5.95703070e+03 -9.55185591e+02 -1.45760182e+02
 -2.04012262e+01 -1.82022002e+05 -3.14060370e+02] -155.44185656249084 [-4.38355644e+04 -9.09893076e+05 -5.56441850e+04 -1.02422923e+04
 -3.75076492e+05 -2.33642368e+05 -6.00612575e+03 -3.52355202e+02
 -8.18282434e+00 -2.27602571e+08 -6.41010305e+02]


In [28]:
def gradient_descent(x, y, w_in, b_in,theta_in, cost_function, gradient_function, alpha, num_iters):
    """
    Performs batch gradient descent to learn theta. Updates theta by taking
    num_iters gradient steps with learning rate alpha.

    Args:
        x : (ndarray): Shape (m, n) Input data (features of the training examples).
        y : (ndarray): Shape (m,) Output data (actual output values for the training examples).
        w_in : (ndarray): Shape (n,) Initial values of parameters (weights) of the linear term.
        theta_in : ndarray): Shape (n,) Initial values of parameters (weights) of the quadratic term.
         
        b_in : (scalar) Initial value of parameter (bias) of the model.
        cost_function : function to compute cost.
        gradient_function : function to compute the gradient.
        alpha : (float) Learning rate.
        num_iters : (int) Number of iterations to run gradient descent.

    Returns:
        w : (ndarray): Shape (n,) Updated values of parameters (weights) of the model after running gradient descent.
        b : (scalar) Updated value of parameter (bias) of the model after running gradient descent.
        J_history : List of costs at each iteration.
        w_history : List of weights at each iteration.
    """
    m, n = x.shape
    # Initialize parameters
    w = copy.deepcopy(w_in)  # Avoid modifying global w within function
    theta=copy.deepcopy(theta_in)
    b = b_in

    # History of cost and weights
    J_history = []
    w_history = []

    for i in range(num_iters):
        # Calculate the gradient and update the parameters
        dj_dw, dj_db,dj_dtheta = gradient_function(x, y, w, b,theta)

        # Update Parameters using w, theta, b, alpha, and gradient
        for j in range(n):
            w[j] = w[j] - alpha * dj_dw[j]
            theta[j] = theta[j] - alpha * dj_dtheta[j]
            b = b - alpha * dj_db

        # Save cost J at each iteration
        if i < 10000000:  # Prevent resource exhaustion
            cost = cost_function(x, y, w, b,theta)
            J_history.append(cost)

        # Print cost every at intervals 10 times or as many iterations if < 10
        if i % math.ceil(num_iters / 100) == 0:
            w_history.append(w.copy())
            print(f"Iteration {i:4}: Cost {float(J_history[-1]):15.2f}")

    return w, b,theta, J_history, w_history  # Return w and J, w history for graphing

In [29]:
import copy
import math
m,n=x_train.shape
initial_w = np.zeros(n)
initial_theta = np.zeros(n)
initial_b=0.5
# Define the learning rate and number of iterations
alpha = 0.00000000000072
iterations = 5000
# Perform gradient descent
w, b, theta,_, _ = gradient_descent(x_train, y_train, initial_w, initial_b,initial_theta, compute_cost, compute_gradient, alpha, iterations)

print("w, b found by gradient descent:", w, b,theta)

Iteration    0: Cost         5601.34
Iteration   50: Cost         2750.22
Iteration  100: Cost         2749.67
Iteration  150: Cost         2749.13
Iteration  200: Cost         2748.58
Iteration  250: Cost         2748.03
Iteration  300: Cost         2747.49
Iteration  350: Cost         2746.94
Iteration  400: Cost         2746.40
Iteration  450: Cost         2745.85
Iteration  500: Cost         2745.31
Iteration  550: Cost         2744.76
Iteration  600: Cost         2744.22
Iteration  650: Cost         2743.68
Iteration  700: Cost         2743.13
Iteration  750: Cost         2742.59
Iteration  800: Cost         2742.05
Iteration  850: Cost         2741.51
Iteration  900: Cost         2740.97
Iteration  950: Cost         2740.43
Iteration 1000: Cost         2739.89
Iteration 1050: Cost         2739.35
Iteration 1100: Cost         2738.81
Iteration 1150: Cost         2738.27
Iteration 1200: Cost         2737.73
Iteration 1250: Cost         2737.19
Iteration 1300: Cost         2736.65
I

KeyboardInterrupt: 

In [114]:
print('The shape of x_test is:', x_test.shape)

The shape of x_test is: (147, 11)


In [116]:
from IPython.display import FileLink
k=x_test.shape[0]
data=[]
f_wb=np.zeros(k)
y_pred=np.zeros(k)
for i in range(k):
        f_wb[i] = b  # Start with the bias term
        
        for j in range(11):  # Sum over all features
            f_wb[i] += w[j] * x_test[i, j]+theta[j] * x_test[i, j]**2
        print(f_wb[i], y_test[i])
        row= [f_wb[i],y_test[i]]
        data.append(row)
        y_pred[i]=f_wb[i]

mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
rmse = mean_squared_error(y_test, y_pred, squared=False)
print(f"Root Mean Squared Error: {rmse}")

-27048.968615780097 248.44263
-92889.2820218933 68.3101602
-14845.509205177448 377.255276
-22114.06729110934 167.079003
50855.69966660773 240.816006
-85896.91918983901 17.0370557
-53770.03258716129 205.014769
-64450.91283288742 107.907488
-6112.389880521395 262.94273
-57215.223101681404 117.235871
-80366.15412823806 74.8783573
-86558.91997120366 61.2762741
-59695.549120355565 223.451568
9648.469600202881 128.826424
-37999.057966542445 199.903596
39057.51190470565 216.394528
-12528.301921533433 163.715925
-73143.5634655371 127.103243
-22919.07631707779 162.872211
-46916.35338715643 133.971542
-18121.237094099786 168.96158
35591.13956392869 279.166532
-13648.703838376037 154.779523
28337.46689275947 240.321946
-92375.86915659346 49.343001
34563.23481702278 209.944732
20348.16601128028 236.362441
-96943.6330349321 63.807184
30406.789371334307 180.072041
-7813.4164670026075 164.795386
-11206.393897646878 177.314467
-84811.92230550319 34.5454599
41397.91112802738 436.789023
-57209.552530265

In [ ]:
df=pd.DataFrame(data,columns=['Predicted','Actual'])
file_name='Result_Polynomiar_Regression2.xlsx'
df.to_excel(file_name, index=False)
FileLink(file_name)