In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import mean_squared_error

In [2]:
file_path = 'Inputs_modified_a.xlsx'
dataset=pd.read_excel(file_path)
x=dataset.iloc[2:,2:-1].values
y=dataset.iloc[2:,-1].values

In [3]:
print(x)

[[52.6 76.6 19.2 ... 0 600 2]
 [52.6 76.6 19.2 ... 0 600 2.3]
 [52.6 76.6 19.2 ... 0 900 1.8]
 ...
 [38.1 66 13.6 ... 0.2388 1500 1.8]
 [38.1 66 13.6 ... 0.2388 1500 2]
 [38.1 66 13.6 ... 0.2388 1500 2.3]]


In [4]:
print(y)

[47.4900692 44.0212568 103.090293 98.0306171 92.0327738 120.695862
 117.973042 114.246795 137.594684 137.103579 135.643063 119.083949
 113.581613 107.325081 223.451568 215.423479 205.202528 256.163744
 252.699618 247.067974 287.612614 288.357209 287.151583 54.5844441
 47.6059779 40.1867174 146.405566 133.971542 120.409132 182.754255
 174.44631 164.795386 217.872122 213.737578 208.129133 171.557512
 168.832244 164.470379 280.128094 277.743054 272.585691 309.384675
 310.907001 310.20901 338.032976 342.998919 346.221891 69.4333031
 65.407838 60.9394313 140.059377 133.864298 126.318114 162.394769
 159.285135 154.779523 183.880081 183.676551 182.167157 40.0930395
 32.8929284 25.2785053 129.029184 115.98735 101.964396 165.852115
 156.800686 146.568687 201.55345 196.573817 190.265646 25.7707222
 18.6693525 11.1905385 105.637114 92.5380291 78.644788 142.324015
 132.897781 122.514736 177.990661 172.341626 165.588549 37.5444388
 35.0107133 32.2489806 77.5150042 73.2956993 68.4072638 91.7893871
 

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.85,test_size=0.15,random_state=0)


In [6]:
print ('The shape of x_train is:', x_train.shape)
print ('The shape of y_train is: ', y_train.shape)
print ('Number of training examples (m):', len(x_train))

The shape of x_train is: (831, 11)
The shape of y_train is:  (831,)
Number of training examples (m): 831


In [7]:
print(f'x_train is numpy array: {isinstance(x_train, np.ndarray)}')
print(f'y_train is numpy array: {isinstance(y_train, np.ndarray)}')

x_train is numpy array: True
y_train is numpy array: True


In [8]:
def compute_cost(x, y, w, b,theta):
    """
    Cost function for quadratic regression
    Returns:
        The cost is calculated using w, theta b as the parameters for quadratic regression
                            to fit the data points in x and y.
    """
    # Number of training examples
    m,n = x.shape

    # Initialize total cost
    total_cost = 0
    f_wb=np.zeros(m)

    # Compute the total cost using a for loop
    for i in range(m):
        f_wb[i] = b  # Start with the bias term
        for j in range(n):  # Sum over all features
            f_wb[i] += w[j] * x[i, j] + theta[j] * x[i, j]**2
        total_cost += (f_wb[i] - y[i]) ** 2  # Sum of squared errors

    # Compute the average cost
    total_cost = total_cost / (2 * m)

    return total_cost

In [9]:
m,n=x_train.shape
initial_w = np.zeros(n)
initial_theta=np.zeros(n)
initial_b =0.5

cost = compute_cost(x_train, y_train, initial_w, initial_b,initial_theta)
print(type(cost))
print(f'Cost at initial w: {cost:.3f}')


<class 'numpy.float64'>
Cost at initial w: 15314.256


In [10]:
def compute_gradient(x, y, w, b,theta):
    """
    The gradient for quadratic regression with multiple variables.
    """
    # Number of training examples
    m, n = x.shape
    total_cost = np.zeros(m)
    # Initialize gradients
    dj_dw = np.zeros(n)
    dj_dtheta = np.zeros(n)
    dj_db = 0.0
    f_wb=np.zeros(m)
    error=np.zeros(m)
    for i in range(m):
        f_wb[i] = np.dot(w.T,x[i,:]) + np.dot(theta.T,x[i,:]**2)+ b  # Predicted value
        error[i] = f_wb[i] - y[i]  # Error term
        for j in range(n):
            dj_dw[j] += error[i] * x[i, j]  # Gradient for w[j]
            dj_dtheta[j] += error[i] * x[i, j]**2
        dj_db += error[i]  # Gradient for b

    # Average the gradients
    dj_dw = (dj_dw) / m
    dj_dtheta = (dj_dtheta) / m
    dj_db= (dj_db)/ m


    return dj_dw, dj_db,dj_dtheta

In [11]:
m,n=x_train.shape
initial_w = np.zeros(n)
initial_theta=np.zeros(n)
initial_b = 0

tmp_dj_dw, tmp_dj_db,tmp_dj_dtheta = compute_gradient(x_train, y_train, initial_w, initial_b,initial_theta)
print(f'dj_dw,dj_dtheta at initial w, b,theta (zeros): {tmp_dj_dw}')
print('Gradient at initial w, b (zeros):', tmp_dj_dw, tmp_dj_db,tmp_dj_dtheta)

dj_dw,dj_dtheta at initial w, b,theta (zeros): [-1.93397960e+03 -1.18554702e+04 -2.84273910e+03 -8.46926755e+02
 -7.61888120e+03 -5.95703070e+03 -9.55185591e+02 -1.45760182e+02
 -2.04012262e+01 -1.82022002e+05 -3.14060370e+02]
Gradient at initial w, b (zeros): [-1.93397960e+03 -1.18554702e+04 -2.84273910e+03 -8.46926755e+02
 -7.61888120e+03 -5.95703070e+03 -9.55185591e+02 -1.45760182e+02
 -2.04012262e+01 -1.82022002e+05 -3.14060370e+02] -155.44185656249084 [-4.38355644e+04 -9.09893076e+05 -5.56441850e+04 -1.02422923e+04
 -3.75076492e+05 -2.33642368e+05 -6.00612575e+03 -3.52355202e+02
 -8.18282434e+00 -2.27602571e+08 -6.41010305e+02]


In [12]:
def gradient_descent(x, y, w_in, b_in,theta_in, cost_function, gradient_function, alpha, num_iters):
    """
    Gradient Descent Calculation
    """
    m, n = x.shape
    # Initialize parameters
    w = copy.deepcopy(w_in)  # Avoid modifying global w within function
    theta=copy.deepcopy(theta_in)
    b = b_in

    # History of cost and weights
    J_history = []
    w_history = []

    for i in range(num_iters):
        # Calculate the gradient and update the parameters
        dj_dw, dj_db,dj_dtheta = gradient_function(x, y, w, b,theta)

        # Update Parameters using w, theta, b, alpha, and gradient
        for j in range(n):
            w[j] = w[j] - alpha * dj_dw[j]
            theta[j] = theta[j] - alpha * dj_dtheta[j]
            b = b - alpha * dj_db

        # Save cost J at each iteration
        if i < 10000000:  # Prevent resource exhaustion
            cost = cost_function(x, y, w, b,theta)
            J_history.append(cost)

        # Print cost every at intervals 10 times or as many iterations if < 10
        if i % math.ceil(num_iters / 100) == 0:
            w_history.append(w.copy())
            print(f"Iteration {i:4}: Cost {float(J_history[-1]):15.2f}")

    return w, b,theta, J_history, w_history  # Return w and J, w history for graphing

In [13]:
import copy
import math
m,n=x_train.shape
initial_w = np.zeros(n)
initial_theta = np.zeros(n)
initial_b=0.5
# Define the learning rate and number of iterations
alpha = 0.00000000000072
iterations = 5000
# Perform gradient descent
w, b, theta,_, _ = gradient_descent(x_train, y_train, initial_w, initial_b,initial_theta, compute_cost, compute_gradient, alpha, iterations)

print("w, b found by gradient descent:", w, b,theta)

Iteration    0: Cost         5601.34
Iteration   50: Cost         2750.22
Iteration  100: Cost         2749.67
Iteration  150: Cost         2749.13
Iteration  200: Cost         2748.58
Iteration  250: Cost         2748.03
Iteration  300: Cost         2747.49
Iteration  350: Cost         2746.94
Iteration  400: Cost         2746.40
Iteration  450: Cost         2745.85
Iteration  500: Cost         2745.31
Iteration  550: Cost         2744.76
Iteration  600: Cost         2744.22
Iteration  650: Cost         2743.68
Iteration  700: Cost         2743.13
Iteration  750: Cost         2742.59
Iteration  800: Cost         2742.05
Iteration  850: Cost         2741.51
Iteration  900: Cost         2740.97
Iteration  950: Cost         2740.43
Iteration 1000: Cost         2739.89
Iteration 1050: Cost         2739.35
Iteration 1100: Cost         2738.81
Iteration 1150: Cost         2738.27
Iteration 1200: Cost         2737.73
Iteration 1250: Cost         2737.19
Iteration 1300: Cost         2736.65
I

In [14]:
print('The shape of x_test is:', x_test.shape)

The shape of x_test is: (147, 11)


In [15]:
from IPython.display import FileLink
k=x_test.shape[0]
data=[]
f_wb=np.zeros(k)
y_pred=np.zeros(k)
for i in range(k):
        f_wb[i] = b  # Start with the bias term
        
        for j in range(11):  # Sum over all features
            f_wb[i] += w[j] * x_test[i, j]+theta[j] * x_test[i, j]**2
        print(f_wb[i], y_test[i])
        row= [f_wb[i],y_test[i]]
        data.append(row)
        y_pred[i]=f_wb[i]

mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
rmse = mean_squared_error(y_test, y_pred, squared=False)
print(f"Root Mean Squared Error: {rmse}")

160.65838707117027 248.44263
42.97235568330906 68.3101602
160.40844418478838 377.255276
160.58112585285815 167.079003
247.76435987701356 240.816006
42.864934697871035 17.0370557
91.50923934642135 205.014769
91.90682866329126 107.907488
159.8770311611262 262.94273
91.77520956679693 117.235871
42.58466941690745 74.8783573
42.64758541501175 61.2762741
91.74558717712388 223.451568
159.90048727243925 128.826424
91.19007775279547 199.903596
248.5349700785859 216.394528
160.2588000447639 163.715925
42.134242188690415 127.103243
160.5373950970788 162.872211
91.43205507654106 133.971542
160.45686521924395 168.96158
248.49307402550681 279.166532
160.15962167338333 154.779523
159.40751625151756 240.321946
42.84569610882381 49.343001
248.59493728799123 209.944732
249.10841246536316 236.362441
43.06344488298221 63.807184
248.78963358834574 180.072041
160.11371128616275 164.795386
160.2327912602941 177.314467
42.757519598504366 34.5454599
248.29990029701258 436.789023
91.77520991562498 103.073153
16

In [16]:
df=pd.DataFrame(data,columns=['Predicted','Actual'])
file_name='Result_Polynomiar_Regression2.xlsx'
df.to_excel(file_name, index=False)
FileLink(file_name)

C:\Users\Mafi\Data file\Result_Polynomiar_Regression2.xlsx